In [1]:
import numpy as np

In [ ]:
# From Python Lists

In [5]:
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [6]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [7]:
# Special Arrays

In [8]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [12]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
np.random.rand(3, 2)

array([[0.00772773, 0.81678975],
       [0.63018367, 0.58607042],
       [0.15539713, 0.84114323]])

In [14]:
np.random.randn(3, 2)

array([[-0.9443231 , -1.43789486],
       [ 0.37132838, -1.36045733],
       [ 0.20104786, -0.39979358]])

In [15]:
#Array Attributes

In [16]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(2, 3)
2
6
int64


In [17]:
#Array Operations

In [18]:
# Basic Math

In [19]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a * b)
np.sin(a)

[5 7 9]
[ 4 10 18]


array([0.84147098, 0.90929743, 0.14112001])

In [20]:
# Matrix Multiplication

In [21]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.dot(A, B)
A @ B

array([[19, 22],
       [43, 50]])

In [22]:
# Aggregation

In [23]:
arr = np.array([1, 2, 3, 4])
print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.min())
print(arr.std())

10
2.5
4
1
1.118033988749895


In [24]:
#Indexing and slicing

In [25]:
# 1D Arrays

In [26]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])
print(arr[1:4])
print(arr[::2])

1
[2 3 4]
[1 3 5]


In [27]:
# 2D Arrays

In [31]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[0, 1])
print(arr[:,1])
print(arr[1,:2])

2
[2 5]
[4 5]


In [32]:
# Boolean Indexing

In [33]:
arr=np.array([1,2,3,4,5])
mask=arr>3
arr[mask]

array([4, 5])

In [ ]:
 #Reshaping and Combining Arrays

In [ ]:
#Reshape

In [34]:
arr = np.arange(6)
arr.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
# Concatenation

In [35]:
a = np.array([1, 2])
b = np.array([3, 4])
np.concatenate((a, b))

array([1, 2, 3, 4])

In [36]:
# Stacking

In [37]:
np.vstack((a, b))
np.hstack((a, b))

array([1, 2, 3, 4])

In [38]:
#Broadcasting

In [39]:
a = np.array([1, 2, 3])
a + 5 # [6, 7, 8]

array([6, 7, 8])

In [ ]:
#Saving amd Loading Arrays

In [ ]:
# Save to a file

In [42]:
np.save('array.npy', arr)

In [43]:
# Load from a file

In [44]:
loaded_arr=np.load('array.npy')